package com.sust.dao;

import com.sust.model.TEnterpriseInfo;
import com.sust.model.TEnterpriseInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TEnterpriseInfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise_info
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    int countByExample(TEnterpriseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise_info
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    int deleteByExample(TEnterpriseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise_info
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise_info
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    int insert(TEnterpriseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise_info
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    int insertSelective(TEnterpriseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise_info
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    List<TEnterpriseInfo> selectByExample(TEnterpriseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise_info
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    TEnterpriseInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise_info
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    int updateByExampleSelective(@Param("record") TEnterpriseInfo record,
            @Param("example") TEnterpriseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise_info
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    int updateByExample(@Param("record") TEnterpriseInfo record, @Param("example") TEnterpriseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise_info
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    int updateByPrimaryKeySelective(TEnterpriseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise_info
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    int updateByPrimaryKey(TEnterpriseInfo record);
}