package com.sust.dao;

import com.sust.model.TItemType;
import com.sust.model.TItemTypeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TItemTypeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_type
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    int countByExample(TItemTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_type
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    int deleteByExample(TItemTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_type
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_type
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    int insert(TItemType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_type
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    int insertSelective(TItemType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_type
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    List<TItemType> selectByExample(TItemTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_type
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    TItemType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_type
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    int updateByExampleSelective(@Param("record") TItemType record, @Param("example") TItemTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_type
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    int updateByExample(@Param("record") TItemType record, @Param("example") TItemTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_type
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    int updateByPrimaryKeySelective(TItemType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_type
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    int updateByPrimaryKey(TItemType record);
}