package com.sust.dao;

import com.sust.model.TRank;
import com.sust.model.TRankExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TRankDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rank
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    int countByExample(TRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rank
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    int deleteByExample(TRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rank
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rank
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    int insert(TRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rank
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    int insertSelective(TRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rank
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    List<TRank> selectByExample(TRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rank
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    TRank selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rank
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    int updateByExampleSelective(@Param("record") TRank record, @Param("example") TRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rank
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    int updateByExample(@Param("record") TRank record, @Param("example") TRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rank
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    int updateByPrimaryKeySelective(TRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rank
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    int updateByPrimaryKey(TRank record);
}