package com.sust.model;

public class TEnterpriseInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise_info.id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise_info.enterprise_id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private String enterpriseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise_info.enterprise_company_name
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private String enterpriseCompanyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise_info.enterprise_link_man
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private String enterpriseLinkMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise_info.enterprise_phone_num
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private String enterprisePhoneNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise_info.enterprise_address
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private String enterpriseAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise_info.enterprise_email
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private String enterpriseEmail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise_info.id
     *
     * @return the value of t_enterprise_info.id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise_info.id
     *
     * @param id the value for t_enterprise_info.id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise_info.enterprise_id
     *
     * @return the value of t_enterprise_info.enterprise_id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public String getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise_info.enterprise_id
     *
     * @param enterpriseId the value for t_enterprise_info.enterprise_id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setEnterpriseId(String enterpriseId) {
        this.enterpriseId = enterpriseId == null ? null : enterpriseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise_info.enterprise_company_name
     *
     * @return the value of t_enterprise_info.enterprise_company_name
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public String getEnterpriseCompanyName() {
        return enterpriseCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise_info.enterprise_company_name
     *
     * @param enterpriseCompanyName the value for t_enterprise_info.enterprise_company_name
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setEnterpriseCompanyName(String enterpriseCompanyName) {
        this.enterpriseCompanyName = enterpriseCompanyName == null ? null : enterpriseCompanyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise_info.enterprise_link_man
     *
     * @return the value of t_enterprise_info.enterprise_link_man
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public String getEnterpriseLinkMan() {
        return enterpriseLinkMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise_info.enterprise_link_man
     *
     * @param enterpriseLinkMan the value for t_enterprise_info.enterprise_link_man
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setEnterpriseLinkMan(String enterpriseLinkMan) {
        this.enterpriseLinkMan = enterpriseLinkMan == null ? null : enterpriseLinkMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise_info.enterprise_phone_num
     *
     * @return the value of t_enterprise_info.enterprise_phone_num
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public String getEnterprisePhoneNum() {
        return enterprisePhoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise_info.enterprise_phone_num
     *
     * @param enterprisePhoneNum the value for t_enterprise_info.enterprise_phone_num
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setEnterprisePhoneNum(String enterprisePhoneNum) {
        this.enterprisePhoneNum = enterprisePhoneNum == null ? null : enterprisePhoneNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise_info.enterprise_address
     *
     * @return the value of t_enterprise_info.enterprise_address
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public String getEnterpriseAddress() {
        return enterpriseAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise_info.enterprise_address
     *
     * @param enterpriseAddress the value for t_enterprise_info.enterprise_address
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setEnterpriseAddress(String enterpriseAddress) {
        this.enterpriseAddress = enterpriseAddress == null ? null : enterpriseAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise_info.enterprise_email
     *
     * @return the value of t_enterprise_info.enterprise_email
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public String getEnterpriseEmail() {
        return enterpriseEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise_info.enterprise_email
     *
     * @param enterpriseEmail the value for t_enterprise_info.enterprise_email
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setEnterpriseEmail(String enterpriseEmail) {
        this.enterpriseEmail = enterpriseEmail == null ? null : enterpriseEmail.trim();
    }
}