package com.sust.model;

import java.math.BigDecimal;

public class TItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.enterprise_id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private String enterpriseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.item_id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private String itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.item_name
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.item_price
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private BigDecimal itemPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.item_pic
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private String itemPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.item_enterprise
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private String itemEnterprise;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.id
     *
     * @return the value of t_item.id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.id
     *
     * @param id the value for t_item.id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.enterprise_id
     *
     * @return the value of t_item.enterprise_id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public String getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.enterprise_id
     *
     * @param enterpriseId the value for t_item.enterprise_id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setEnterpriseId(String enterpriseId) {
        this.enterpriseId = enterpriseId == null ? null : enterpriseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.item_id
     *
     * @return the value of t_item.item_id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.item_id
     *
     * @param itemId the value for t_item.item_id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.item_name
     *
     * @return the value of t_item.item_name
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.item_name
     *
     * @param itemName the value for t_item.item_name
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.item_price
     *
     * @return the value of t_item.item_price
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public BigDecimal getItemPrice() {
        return itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.item_price
     *
     * @param itemPrice the value for t_item.item_price
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setItemPrice(BigDecimal itemPrice) {
        this.itemPrice = itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.item_pic
     *
     * @return the value of t_item.item_pic
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public String getItemPic() {
        return itemPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.item_pic
     *
     * @param itemPic the value for t_item.item_pic
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setItemPic(String itemPic) {
        this.itemPic = itemPic == null ? null : itemPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.item_enterprise
     *
     * @return the value of t_item.item_enterprise
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public String getItemEnterprise() {
        return itemEnterprise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.item_enterprise
     *
     * @param itemEnterprise the value for t_item.item_enterprise
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setItemEnterprise(String itemEnterprise) {
        this.itemEnterprise = itemEnterprise == null ? null : itemEnterprise.trim();
    }
}