package com.sust.model;

public class TItemType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_type.id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_type.item_type_id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private Byte itemTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_type.item_type_desc
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private String itemTypeDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_type.id
     *
     * @return the value of t_item_type.id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_type.id
     *
     * @param id the value for t_item_type.id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_type.item_type_id
     *
     * @return the value of t_item_type.item_type_id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public Byte getItemTypeId() {
        return itemTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_type.item_type_id
     *
     * @param itemTypeId the value for t_item_type.item_type_id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setItemTypeId(Byte itemTypeId) {
        this.itemTypeId = itemTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_type.item_type_desc
     *
     * @return the value of t_item_type.item_type_desc
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public String getItemTypeDesc() {
        return itemTypeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_type.item_type_desc
     *
     * @param itemTypeDesc the value for t_item_type.item_type_desc
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setItemTypeDesc(String itemTypeDesc) {
        this.itemTypeDesc = itemTypeDesc == null ? null : itemTypeDesc.trim();
    }
}