package com.sust.model;

import java.math.BigDecimal;
import java.util.Date;

public class TOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_content
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private String orderContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_price
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private BigDecimal orderPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.dispatch_address
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private String dispatchAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.expect_time
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private String expectTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_status
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private Byte orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.create_time
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.update_time
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.id
     *
     * @return the value of t_order.id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.id
     *
     * @param id the value for t_order.id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_id
     *
     * @return the value of t_order.order_id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_id
     *
     * @param orderId the value for t_order.order_id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_content
     *
     * @return the value of t_order.order_content
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public String getOrderContent() {
        return orderContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_content
     *
     * @param orderContent the value for t_order.order_content
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setOrderContent(String orderContent) {
        this.orderContent = orderContent == null ? null : orderContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_price
     *
     * @return the value of t_order.order_price
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public BigDecimal getOrderPrice() {
        return orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_price
     *
     * @param orderPrice the value for t_order.order_price
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setOrderPrice(BigDecimal orderPrice) {
        this.orderPrice = orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.dispatch_address
     *
     * @return the value of t_order.dispatch_address
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public String getDispatchAddress() {
        return dispatchAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.dispatch_address
     *
     * @param dispatchAddress the value for t_order.dispatch_address
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setDispatchAddress(String dispatchAddress) {
        this.dispatchAddress = dispatchAddress == null ? null : dispatchAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.expect_time
     *
     * @return the value of t_order.expect_time
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public String getExpectTime() {
        return expectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.expect_time
     *
     * @param expectTime the value for t_order.expect_time
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setExpectTime(String expectTime) {
        this.expectTime = expectTime == null ? null : expectTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_status
     *
     * @return the value of t_order.order_status
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public Byte getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_status
     *
     * @param orderStatus the value for t_order.order_status
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setOrderStatus(Byte orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.create_time
     *
     * @return the value of t_order.create_time
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.create_time
     *
     * @param createTime the value for t_order.create_time
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.update_time
     *
     * @return the value of t_order.update_time
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.update_time
     *
     * @param updateTime the value for t_order.update_time
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}