package com.sust.model;

public class TRank {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rank.id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rank.rank_id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private Byte rankId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rank.rank_desc
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private String rankDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rank.id
     *
     * @return the value of t_rank.id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rank.id
     *
     * @param id the value for t_rank.id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rank.rank_id
     *
     * @return the value of t_rank.rank_id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public Byte getRankId() {
        return rankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rank.rank_id
     *
     * @param rankId the value for t_rank.rank_id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setRankId(Byte rankId) {
        this.rankId = rankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rank.rank_desc
     *
     * @return the value of t_rank.rank_desc
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public String getRankDesc() {
        return rankDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rank.rank_desc
     *
     * @param rankDesc the value for t_rank.rank_desc
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setRankDesc(String rankDesc) {
        this.rankDesc = rankDesc == null ? null : rankDesc.trim();
    }
}