package com.sust.model;

import java.util.Date;

public class TUserAndOrderRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_and_order_relation.id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_and_order_relation.user_id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_and_order_relation.order_id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_and_order_relation.create_time
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_and_order_relation.update_time
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_and_order_relation.id
     *
     * @return the value of t_user_and_order_relation.id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_and_order_relation.id
     *
     * @param id the value for t_user_and_order_relation.id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_and_order_relation.user_id
     *
     * @return the value of t_user_and_order_relation.user_id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_and_order_relation.user_id
     *
     * @param userId the value for t_user_and_order_relation.user_id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_and_order_relation.order_id
     *
     * @return the value of t_user_and_order_relation.order_id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_and_order_relation.order_id
     *
     * @param orderId the value for t_user_and_order_relation.order_id
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_and_order_relation.create_time
     *
     * @return the value of t_user_and_order_relation.create_time
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_and_order_relation.create_time
     *
     * @param createTime the value for t_user_and_order_relation.create_time
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_and_order_relation.update_time
     *
     * @return the value of t_user_and_order_relation.update_time
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_and_order_relation.update_time
     *
     * @param updateTime the value for t_user_and_order_relation.update_time
     *
     * @mbggenerated Thu Apr 19 15:58:57 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}